//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkaApp.Models.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArkaAppEntities : DbContext
    {
        public ArkaAppEntities()
            : base("name=ArkaAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<ApiLog> ApiLog { get; set; }
        public virtual DbSet<CommentLog> CommentLog { get; set; }
        public virtual DbSet<CommentLogDetail> CommentLogDetail { get; set; }
        public virtual DbSet<Content> Content { get; set; }
        public virtual DbSet<DirectContentLog> DirectContentLog { get; set; }
        public virtual DbSet<DirectContentLogDetail> DirectContentLogDetail { get; set; }
        public virtual DbSet<DirectLog> DirectLog { get; set; }
        public virtual DbSet<DirectLogDetail> DirectLogDetail { get; set; }
        public virtual DbSet<ExploreLog> ExploreLog { get; set; }
        public virtual DbSet<Follower> Follower { get; set; }
        public virtual DbSet<FollowerDetail> FollowerDetail { get; set; }
        public virtual DbSet<FollowerGenderDetail> FollowerGenderDetail { get; set; }
        public virtual DbSet<FollowerLog> FollowerLog { get; set; }
        public virtual DbSet<FollowerLogDetail> FollowerLogDetail { get; set; }
        public virtual DbSet<LikeLog> LikeLog { get; set; }
        public virtual DbSet<LikeLogDetail> LikeLogDetail { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MenuRole> MenuRole { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<TelegramContentLog> TelegramContentLog { get; set; }
        public virtual DbSet<TelegramContentLogDetail> TelegramContentLogDetail { get; set; }
        public virtual DbSet<TelegramLog> TelegramLog { get; set; }
        public virtual DbSet<TelegramLogDetail> TelegramLogDetail { get; set; }
        public virtual DbSet<TelegramUserContentLog> TelegramUserContentLog { get; set; }
        public virtual DbSet<TelegramUserContentLogDetail> TelegramUserContentLogDetail { get; set; }
        public virtual DbSet<TelegramUserLog> TelegramUserLog { get; set; }
        public virtual DbSet<TelegramUserLogDetail> TelegramUserLogDetail { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<ViewLog> ViewLog { get; set; }
        public virtual DbSet<ViewLogDetail> ViewLogDetail { get; set; }
        public virtual DbSet<WalletChargeLog> WalletChargeLog { get; set; }
        public virtual DbSet<WalletPaymentLog> WalletPaymentLog { get; set; }
        public virtual DbSet<Pricing> Pricing { get; set; }
        public virtual DbSet<PricingDetail> PricingDetail { get; set; }
    }
}
