//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkaApp.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExploreLog
    {
        public int ExploreLogID { get; set; }
        public int PostID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FromDateFa { get; set; }
        public Nullable<System.DateTime> FromDateEn { get; set; }
        public Nullable<int> DateCount { get; set; }
        public string EndDateFa { get; set; }
        public Nullable<System.DateTime> EndDateEn { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
