//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkaApp.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricing
    {
        public int PricingID { get; set; }
        public string Title { get; set; }
        public string TitleFa { get; set; }
        public int Count { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
