//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkaApp.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelegramUserContentLogDetail
    {
        public int TelegramUserContentLogDetailID { get; set; }
        public Nullable<int> TelegramUserContentLogID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> Count { get; set; }
    
        public virtual TelegramUserContentLog TelegramUserContentLog { get; set; }
    }
}
