//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkaApp.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletPaymentLog
    {
        public int WalletPaymentLogID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> LogID { get; set; }
        public string LogType { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
